### ISSUE TITLE
401 Errors

### ISSUE THREAD

**Issue by jonathancadepowers** [codeclimate/ruby-test-reporter#58]
We've received some reports of receiving a 401 error when POSTing us test coverage.

```bash
Coverage = 98.86%. Sending report to https://codeclimate.com for branch master... Code Climate encountered an exception: RuntimeError
HTTP Error: 401
```
In these events, first ensure the token you are using is 100% correct. If it is, see the work-around listed here: https://github.com/codeclimate/ruby-test-reporter/issues/28#issuecomment-60523477

If this does not resolve the issue, please let us know via [a support ticket](https://codeclimate.com/help).

**Comment by arielkirkwood** [comment]
@jonathancadepowers I'm getting a 401 error running my tests on Travis CI, I have the Code Climate repo token set in my `.travis.yml` like so:
```
addons:
  code_climate:
    repo_token:
      secure: "nzptHCQX610FaKENHdeXiMe6oDXj4NrhQ91RD4M5cZmCpATeKlDUERjNK7tcHX8Y+miG9ZLJ5/p6iH28p7MkQN9GP8AfvQ0r9UwY007at1W2HTpj4A5Fg2OzOdG4hhWjVM3NRK8NeFC56OVVjTzhKww+vktzElQHICXA72NDJbo="
```
where the value after `secure:` is the output of `travis encrypt CODECLIMATE_REPO_TOKEN=<repo token copied/pasted from Code Climate site>`

Locally on my own machine, running `CODECLIMATE_REPO_TOKEN=<repo token copied/pasted from Code Climate site> bundle exec rake` exactly as recommended in the "Set up Test Coverage" section of Code Climate worked without a problem.

Let me know if there's any further information I can provide, or if I'm barking up the wrong tree.
